name: Obico ML Home Assistant Addon
version: 1.0.0
version: dev
slug: obico_ml_ha_addon
description: "Home Assistant addon for integrating Obico ML-based monitoring."
ports:
  3333/tcp: 3333
webui: "http://[HOST]:[PORT:3333]"
url: https://github.com/nobodyguy/obico_ml_ha_addon
image: "ghcr.io/droidik/obico_ml_ha_addon"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
healthcheck:
  enabled: true
  interval: 30s
  timeout: 10s
  retries: 3